# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'yaml'
plantvillage_config = YAML::load_file(File.join(__dir__, '.plantvillage.secret.yml'))

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "dummy"
  config.vm.provision :shell, path: "bootstrap.sh"
  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder "../plantvillage-common", "/plantvillage-common"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.box = "dummy"

  config.vm.provider :aws do |aws, override|
      # To be filled by user
      aws.access_key_id = plantvillage_config['aws_access_key_id']
      aws.secret_access_key = plantvillage_config['aws_secret_access_key']
      aws.keypair_name = plantvillage_config['aws_keypair_name']
      override.ssh.username = "ubuntu"
      override.ssh.private_key_path = plantvillage_config['aws_private_key_path'] #path/to/private/key

      aws.security_groups = ["SSH Only"]
      aws.ami = "ami-47a23a30" #http://cloud-images.ubuntu.com/releases/14.04/release-20150325/
      aws.region = "eu-west-1"
      aws.instance_type = "g2.2xlarge"
      #aws.elastic_ip = plantvillage_config['aws_elastic_ip']

      aws.block_device_mapping = [
          {
              'DeviceName' => "/dev/sdb",
              'VirtualName' => "plantvillage_data",
              'Ebs.VolumeSize' => 150,
              'Ebs.DeleteOnTermination' => true,
          }
      ]

  end
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   sudo apt-get update
  #   sudo apt-get install -y apache2
  # SHELL
end
